# Generated by Django 5.2.7 on 2026-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_deposit_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deposit',
            name='payments_de_provide_acaec1_idx',
        ),
        migrations.RenameIndex(
            model_name='deposit',
            new_name='payments_de_user_id_e9fc0c_idx',
            old_name='payments_de_user_st_idx',
        ),
        migrations.RenameIndex(
            model_name='deposit',
            new_name='payments_de_user_id_105561_idx',
            old_name='payments_de_user_ct_idx',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='channel',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
