# Generated by Django 5.2.7 on 2026-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wallet_reserved_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='api_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='api_reserved_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
