# Generated by Django 5.2.7 on 2026-06-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_wallet_api_balance_wallet_api_reserved_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.CharField(choices=[('socialpulse', 'SocialPulse'), ('cardpulse', 'CardPulse')], db_index=True, default='socialpulse', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
