# Generated by Django 5.2.7 on 2026-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
