# Generated by Django 5.2.7 on 2026-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
