# Generated by Django 5.2.7 on 2026-06-30 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giftcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('giftcard', 'Giftcard')], max_length=10)),
                ('amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('note', models.CharField(blank=True, default='', max_length=140)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='giftcards.giftcard')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='p2p_transfe_sender__5febb7_idx'), models.Index(fields=['recipient', '-created_at'], name='p2p_transfe_recipie_a14202_idx')],
            },
        ),
    ]
