# Generated by Django 5.2.7 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recv_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recv_currency',
            field=models.CharField(default='NGN', max_length=5),
        ),
    ]
