# Generated by Django 5.2.7 on 2025-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boostrequest',
            name='boost_type',
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='audience',
            field=models.CharField(default='Nigeria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='service',
            field=models.CharField(default='Nigeria', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boostrequest',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('Spotify', 'Spotify')], max_length=50),
        ),
    ]
