# Generated by Django 5.2.7 on 2025-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0002_remove_boostrequest_boost_type_boostrequest_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrequest',
            name='smm_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='smm_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='smm_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='smm_remains',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='smm_start_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boostrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Partial', 'Partial'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
