# Generated by Django 5.2.7 on 2025-10-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0003_boostrequest_smm_charge_boostrequest_smm_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
