# Generated by Django 5.2.7 on 2025-10-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0004_boostrequest_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrequest',
            name='quality',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='boostrequest',
            name='traffic_source',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Wikipedia', 'Wikipedia'), ('Bing', 'Bing'), ('Yahoo', 'Yahoo'), ('Fiverr', 'Fiverr'), ('VK', 'VK.com'), ('Ebay', 'Ebay.com.au'), ('Abc', 'Abc.net.au'), ('News', 'News.com.au'), ('Gumtree', 'Gumtree.com.au')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boostrequest',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('Spotify', 'Spotify'), ('Website Traffic', 'Website Traffic')], max_length=50),
        ),
    ]
