# Generated by Django 5.2.7 on 2026-06-29 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0005_boostrequest_quality_boostrequest_traffic_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boostrequest',
            index=models.Index(fields=['user', 'status'], name='boost_boost_user_id_0987b6_idx'),
        ),
        migrations.AddIndex(
            model_name='boostrequest',
            index=models.Index(fields=['user', '-created_at'], name='boost_boost_user_id_5c8f82_idx'),
        ),
        migrations.AddIndex(
            model_name='boostrequest',
            index=models.Index(fields=['smm_order_id'], name='boost_boost_smm_ord_cb880e_idx'),
        ),
    ]
