# Generated by Django 5.2.7 on 2026-06-30 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('bank_code', models.CharField(max_length=12)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_code', models.CharField(blank=True, default='', max_length=64)),
                ('transfer_code', models.CharField(blank=True, default='', max_length=64)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='processing', max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='banking_wit_user_id_c53487_idx'), models.Index(fields=['status', '-created_at'], name='banking_wit_status_b811af_idx')],
            },
        ),
    ]
