# Generated by Django 5.2.7 on 2026-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
