# Generated by Django 5.2.7 on 2026-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnumber',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualnumber',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualnumber',
            name='sms_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualnumber',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
