# Generated by Django 5.2.7 on 2026-06-29 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualnumbers', '0002_virtualnumber_cancelled_at_virtualnumber_charged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='virtualnumber',
            index=models.Index(fields=['user', 'charged'], name='virtualnumb_user_id_576436_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualnumber',
            index=models.Index(fields=['user', '-created_at'], name='virtualnumb_user_id_1da67c_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualnumber',
            index=models.Index(fields=['activation_id'], name='virtualnumb_activat_bfea2c_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualnumber',
            index=models.Index(fields=['status', 'charged', 'created_at'], name='virtualnumb_status_31e036_idx'),
        ),
    ]
