# Generated by Django 5.2.7 on 2026-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualnumbers', '0003_virtualnumber_virtualnumb_user_id_576436_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnumber',
            name='funding_source',
            field=models.CharField(default='wallet', max_length=10),
        ),
    ]
