# Generated by Django 5.2.7 on 2026-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualnumbers', '0004_virtualnumber_funding_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='virtualnumber',
            name='virtualnumb_activat_bfea2c_idx',
        ),
        migrations.AlterField(
            model_name='virtualnumber',
            name='activation_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
