# Generated by Django 5.2.7 on 2026-06-30 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('face_value_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('code_encrypted', models.TextField(blank=True, default='')),
                ('pin_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('owned', 'Owned'), ('revealed', 'Revealed'), ('traded', 'Traded'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('source', models.CharField(choices=[('minted', 'Minted'), ('traded', 'Traded back')], default='minted', max_length=8)),
                ('redeemable', models.BooleanField(default=True)),
                ('reloadly_transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('custom_identifier', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, default='', max_length=160)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('reloadly_transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='giftcards.giftcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['owner', '-created_at'], name='giftcards_g_owner_i_fe7a25_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['status', 'redeemable'], name='giftcards_g_status_d15339_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['product_id', 'status'], name='giftcards_g_product_25aeae_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardorder',
            index=models.Index(fields=['user', '-created_at'], name='giftcards_g_user_id_0809f9_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardorder',
            index=models.Index(fields=['status'], name='giftcards_g_status_581525_idx'),
        ),
    ]
