# Generated by Django 5.2.7 on 2026-06-30 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('value_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('payout_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending_review', 'Pending review'), ('rejected', 'Rejected')], default='completed', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='giftcards.giftcard')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trades', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='giftcards_g_user_id_f7b186_idx'), models.Index(fields=['status', '-created_at'], name='giftcards_g_status_7e272b_idx')],
            },
        ),
    ]
