# Generated by Django 5.2.7 on 2026-06-30 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_giftcardtrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('code_encrypted', models.TextField(blank=True, default='')),
                ('image_base64', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_validation', 'Pending validation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_validation', max_length=20)),
                ('payout_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('validation_ref', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sales', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='giftcards_g_user_id_4069fe_idx'), models.Index(fields=['status', '-created_at'], name='giftcards_g_status_950fc8_idx')],
            },
        ),
    ]
